### PR TITLE
Farzaneh bug

### LINKED ISSUE #77: Bug: Save new token if it is new
Currently we only save ther token when a new user is created. See [this code](https://github.com/karleenmsrichards/final-project-gp2/blob/development/server/controller/apiController.js). We want to check if the token exists everytime and if it does not create the token
 
- A User can have many tokens
- Tokens will eventually expire
- The User will then need to authenticate via Goggle again
- This creates a new token 
- We then check if the token exists for the user in the DB already
- We will need to save the token to the database

### PR DESCRIPTION
**Pull request by farzaneh-haghani**
## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Bug fixed, User can have many tokens.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #77 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

File: server/api.js [hunk 1]
```diff
@@ -42,12 +38,17 @@ router.post("/validation", async (req, res) => {
...
 		if (!user) {
-			persistNewUser(name, email, role, token);
+			user = persistNewUser(name, email, role);
+			persistNewToken(user.id, token);
 		} else {
-			res.status(200).json({ message: "success" });
+			let currentUser = await Tokens.findOne({ where: { token } });
+			if (!currentUser) {
+				persistNewToken(user.id, token);
+			}
```
Comment (jarrodruby) [inline server/api.js:47]: copy paste error.

File: server/controller/apiController.js [hunk 2]
```diff
@@ -1,8 +1,12 @@
...
-export async function persistNewUser(name, email, role, token) {
+export async function persistNewUser(name, email, role) {
 	const newUser = await Users.create({ name, email, role });
-	await Tokens.create({ token, user_id: newUser.id });
+	return newUser;
+}
+
+export async function persistNewToken(id, token) {
+	await Tokens.create({ token, user_id: id });
 }
```
Comment (jarrodruby) [inline server/controller/apiController.js:11]:
```javascript

function persistLatestToken(user_id, token) {
  let currentToken = await Tokens.findOne({ where: { token } });
  if (!currentToken) { // we only want to persist if it is new
     	await Tokens.create({ token, user_id: id });
  }
  
}

persistNewToken(user.id, token);



```

**Review by jarrodruby — CHANGES_REQUESTED** [review]

**Review by jarrodruby — APPROVED** [review]
